workflows:
  android-workflow:
    name: Android Workflow
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
    scripts:
      - name: Generate Flutter project structure
        script: |
          cp lib/main.dart /tmp/main.dart
          rm -rf *
          rm -rf .git
          flutter create --template=app --project-name=Calculadora Icumsa --org=com.lab.icumsa .
          cp /tmp/main.dart lib/main.dart
      - name: Build APK
        script: |
          flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/*.apk
